# -*- coding: utf-8 -*-
"""CL_ML_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1RSmm7SgbBb_zwFwKzTyD3OvX6FCiYd
"""

from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

import pandas as pd

CSV_COLUMN_NAMES = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species'] # the features in the data used to determind which class
SPECIES = ['Setosa', 'Versicolor', 'Virginica'] # the classes

train_path =tf.keras.utils.get_file("iris_training.csv", "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv")
test_path = tf.keras.utils.get_file(
    "iris_test.csv", "https://storage.googleapis.com/download.tensorflow.org/data/iris_test.csv")

train = pd.read_csv(train_path, names=CSV_COLUMN_NAMES, header=0) # to load the csv file.
test = pd.read_csv(test_path, names=CSV_COLUMN_NAMES, header=0)

train.head() # just shows the dataframe created with the line train = ... above. used to take a look at the data

train_y = train.pop("Species")
test_y = test.pop("Species") # to remove the lable (species)